config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :categories do
    resources :expenditures, only: %i[index create new]
  end
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :expenditure_category, dependent: :destroy
  has_many :category, through: :expenditure_category
  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/controllers/expenditures_controller.rb
class ExpendituresController < ApplicationController
  before_action :authenticate_user!

  before_action :set_category

  # GET /expenditures or /expenditures.json
  def index
    @category = Category.find(params[:category_id])
    @expenditures = @category.expenditures.order(created_at: :desc)
  end

  # GET /expenditures/1 or /expenditures/1.json
  def show; end

  # GET /expenditures/new
  def new
    @expenditure = Expenditure.new
    @category = Category.find(params[:category_id])
  end

  # GET /expenditures/1/edit
  def edit; end

  # POST /expenditures or /expenditures.json
  def create
    @user = current_user
    expenditure_params[:category_ids].each do |category_id|
      @expenditure = Expenditure.new(expenditure_params)
      @expenditure.author_id = @user.id
      @expenditure.category_id = category_id

      next if @expenditure.valid? && @expenditure.save

      puts @expenditure.errors.full_messages
      render :new
      break
    end

    redirect_to category_expenditures_path(@category), notice: 'Trade Records created successfully.'
  end

  # PATCH/PUT /expenditures/1 or /expenditures/1.json
  def update
    respond_to do |format|
      if @expenditure.update(expenditure_params)
        format.html { redirect_to expenditure_url(@expenditure), notice: 'Expenditure was successfully updated.' }
        format.json { render :show, status: :ok, location: @expenditure }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expenditure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenditures/1 or /expenditures/1.json
  def destroy
    @expenditure.destroy

    respond_to do |format|
      format.html { redirect_to expenditures_url, notice: 'Expenditure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:category_id])
  end

  # Only allow a list of trusted parameters through.
  def expenditure_params
    params.require(:expenditure).permit(:name, :amount, category_ids: [])
  end
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/views/expenditures/_expenditure.html.erb
<div id="<%= dom_id expenditure %>">
  <p>
    <strong>Name:</strong>
    <%= expenditure.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= expenditure.amount %>
  </p>

</div>

app/views/expenditures/_form.html.erb
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<div class='Login-form cat-page'>       
<%= form_with model: @expenditure, url: category_expenditures_path(@category) do |form| %>
  <div class="mb-3 field">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3 field">
    <%= form.label :amount, class: 'form-label' %>
    <%= form.number_field :amount, class: 'form-control' %>
  </div>

  <div class=" mb-3 field">
    <%= form.label :category_ids, "choose Categories" %>
    <% current_user.categories.each do |category| %>
    
      <div class="">
        <%= check_box_tag 'expenditure[category_ids][]', category.id, @expenditure.category_ids.include?(category.id) %>
        <%= label_tag "expenditure_category_ids_#{category.id}", category.name %>
      </div>
    <% end %>
  </div>

  <div class="actions-submit">
    <%= form.submit "Create Trade Record" %>
  </div>
<% end %>
</div>

app/views/expenditures/edit.html.erb
<h1>Editing expenditure</h1>

<%= render "form", expenditure: @expenditure %>

<br>

<div>
  <%= link_to "Show this expenditure", @expenditure %> |
  <%= link_to "Back to expenditures", expenditures_path %>
</div>

app/views/expenditures/index.html.erb
<%= render partial: 'shared/nav', locals: {title:'TRANSACTION', symbol:'←', url: :back}%>
<p style="color: green"><%= notice %></p>
<ul class="expense-ul">
  <% @expenditures.each do |expense| %>
    <li class="expenditure-items">
      <strong>Name:</strong> <%= expense.name %>
      <br>
      <strong>Amount:</strong> <%= expense.amount %>
    </li>
  <% end %>
</ul>



<div class="container-make-category">
<%= link_to 'Create Expense', new_category_expenditure_path(@category), class: "make-category"  %>
</div>

app/views/expenditures/new.html.erb
<%= render partial: 'shared/nav', locals: {title:'NEW EXPENDITURE', symbol:'←', url: :back}%>

<%= render "form", expenditure: @expenditure %>

<br>

<div>
  <%= link_to "Back to expenditures", categories_path %>
</div>

app/views/expenditures/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expenditure %>

<div>
  <%= link_to "Edit this expenditure", edit_expenditure_path(@expenditure) %> |
  <%= link_to "Back to expenditures", expenditures_path %>

  <%= button_to "Destroy this expenditure", @expenditure, method: :delete %>
</div>