config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :categories do
    resources :expenditures, only: %i[index create new]
  end
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :expenditure_category, dependent: :destroy
  has_many :expenditures, through: :expenditure_category
  validates :name, presence: true, length: { minimum: 1, maximum: 25 }
  validates :icon, presence: true
end

app/controllers/categories_controller.rb
# The CategoriesController handles CRUD operations for categories in your Rails application.

class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
    if @category.author != current_user
      flash[:alert] = 'Not authorized!'
      redirect_to categories_path
    end
    @expenditure = @category.expenditures.order(created_at: :desc)
    puts @expenditures
    @total = @expenditure.sum(:amount)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.author = current_user
    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div class="category-container" id="<%= dom_id category %>">

  <div class='flex'>
  <img src='<%= category.icon%>'/>
  
    <div class="flex name-time">
      <p><%= category.name %></p>
      <p><%= category.created_at.strftime("%B %d, %Y") %></P>
    </div>
  </div>

  <div class="amount">
    $<%= category.expenditures.sum(:amount) %>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class= 'Login-form'>
  <div class="mb-3 field">
    <%= form.label :name,class: 'form-label', style: "display: block" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3 field">
    <%= form.label :icon, class: 'form-label', style: "display: block" %>
    <%= form.text_field :icon, class: 'form-control' %>
  </div>


  <div class="actions-submit">
    <%= form.submit "Create New Category" %>
  </div></div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<%= render partial: 'shared/nav', locals: {title:'CATEGORIES', symbol:'←', url: :back}%>
<p style="color: green"><%= notice %></p>

<% @categories.each do |category| %>
  <%= link_to category_path(category) do %>
    <div class="categories-index" id="categories">
      <%= render category %>
      
    </div>
  <% end %>
<% end %>


<div class="container-make-category">
<%= link_to "Create New category", new_category_path, class: "make-category" %>
</div>

app/views/categories/new.html.erb
<%= render partial: 'shared/nav', locals: {title:'NEW CATEGORY', symbol:'←', url: :back}%>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<%= render partial: 'shared/nav', locals: {title:'TRANSACTION', symbol:'←', url: :back}%>
<p style="color: green"><%= notice %></p>
<div class="amount">
    $<%= @category.expenditures.sum(:amount) %> Total Transactions
  </div>
<ul class="expense-ul">
  <% @category.expenditures.each do |expense| %>
    <li class="expenditure-items">
      <strong>Name:</strong> <%= expense.name %>
      <br>
      <strong>Amount:</strong> <%= expense.amount %>
    </li>
  <% end %>
</ul>



<div class="container-make-category">
<%= link_to 'Add New Transaction', new_category_expenditure_path(@category), class: "make-category"  %>
</div>